title: Satellite Data Project Report
description: ''

remote_theme: oinam/oinam-jekyll

footer:
  credit: false
  custom: true

footer_custom: '© <script>document.write(new Date().getFullYear())</script>. All Rights Reserved. <a href="https://valinor.earth" target="_blank">Valinor Earth, Inc.</a>'

markdown: kramdown
permalink: pretty

styles:
  font_family: mixed-serif
  forms: true
  syntax_highlighter: false

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

optional_front_matter:
  remove_originals: true

plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - README.*
  - CNAME